# Machine Learning Zoomcamp


## 1.7 Introduction to NumPy


Plan:

* Creating arrays
* Multi-dimensional arrays
* Randomly generated arrays
* Element-wise operations
    * Comparison operations
    * Logical operations
* Summarizing operations

In [1]:
import numpy as np

In [3]:
np

<module 'numpy' from '/Users/ringoyen/anaconda3/lib/python3.11/site-packages/numpy/__init__.py'>

## Creating arrays


In [5]:
np.zeros(10) # adding comment

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [11]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [12]:
np.full(10, 2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [15]:
a = np.array([1, 2, 3, 5, 7, 12])
a

array([ 1,  2,  3,  5,  7, 12])

In [17]:
a[2] = 10

In [18]:
a

array([ 1,  2, 10,  5,  7, 12])

In [43]:
np.arange(3, 11)

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [41]:
np.linspace(0, 100, 5)

array([  0.,  25.,  50.,  75., 100.])

## Multi-dimensional arrays


In [9]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [11]:
n = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [13]:
n[0, 1] = 20

In [15]:
n

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [17]:
n[2] = [1, 1, 1]

In [19]:
n

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 1,  1,  1]])

In [63]:
n[0,:] = [5,6,7]

In [65]:
# n[:, 2] = [0, 1, 5]

In [67]:
n

array([[5, 6, 7],
       [6, 5, 1],
       [7, 1, 5]])

## Randomly generated arrays


In [37]:
np.random.seed(2) # seed allows for it to be psedo-random. allows for the randomness to be controlled
100 * np.random.rand(5, 2)

array([[43.59949021,  2.59262318],
       [54.96624779, 43.53223926],
       [42.03678021, 33.0334821 ],
       [20.4648634 , 61.92709664],
       [29.96546737, 26.68272751]])

In [50]:
np.random.seed(2)
np.random.randn(5, 2)

array([[-0.41675785, -0.05626683],
       [-2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809],
       [-1.05795222, -0.90900761]])

In [69]:
np.random.seed(2)
np.random.randint(low=0, high=100, size=(5, 2))

array([[40, 15],
       [72, 22],
       [43, 82],
       [75,  7],
       [34, 49]])

## Element-wise operations


In [72]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [80]:
b = (10 + (a * 2)) ** 2 / 100

In [82]:
b

array([1.  , 1.44, 1.96, 2.56, 3.24])

In [84]:
a / b + 100

array([100.        , 100.69444444, 101.02040816, 101.171875  ,
       101.2345679 ])

## Comparison operations

In [117]:
a

array([  0,   1,   2,   3,   4, -55])

In [119]:
a >= 3

array([False, False, False,  True,  True, False])

In [127]:
b = np.append(b,55)

In [129]:
a > b

array([False, False,  True,  True,  True, False])

In [131]:
a[a > b]

array([2, 3, 4])

## Summarizing operations

In [101]:
a

array([0, 1, 2, 3, 4])

In [109]:
a = np.append(a,-55)

In [111]:
a.std()

21.2818388929779

In [113]:
np.min(a)

-55

### Next

Linear algebra refresher